import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {handler,prepareImage} from '../lib/core.js';
import sharp from 'sharp';
process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SECRET_KEY='sb_secret_test_only';
const originalFetch=globalThis.fetch;after(()=>globalThis.fetch=originalFetch);
const csrf='a'.repeat(64),sid='b'.repeat(64),uid='11111111-1111-4111-8111-111111111111',itemId='22222222-2222-4222-8222-222222222222';
function response(data,status=200){return new Response(status===204?null:JSON.stringify(data),{status,headers:{'content-type':'application/json'}});}
function request(method='GET',body,query=''){return{method,url:'/api/test'+query,headers:{host:'localhost:3000',origin:'http://localhost:3000','content-type':'application/json',cookie:`hm_csrf=${csrf}; hm_session=${sid}`,'x-csrf-token':csrf},socket:{remoteAddress:'127.0.0.1'},body};}
function out(){return{headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v;},getHeader(k){return this.headers[k];},end(v){this.data=v;}};}
async function call(action,req){const res=out();await handler(action)(req,res);return{...res,json:Buffer.isBuffer(res.data)?null:JSON.parse(res.data)};}
function withRole(role,extra){globalThis.fetch=async(url,options={})=>{const u=new URL(url);if(u.pathname.endsWith('/hm_sessions'))return response(options.method==='PATCH'?null:[{user_id:uid,expires_at:new Date(Date.now()+3600000).toISOString(),last_seen:new Date().toISOString()}],options.method==='PATCH'?204:200);if(u.pathname.endsWith('/hm_profiles'))return response([{user_id:uid,name:'Test',role}]);return extra(u,options);};}
test('mutation without valid CSRF is refused before upstream calls',async()=>{let calls=0;globalThis.fetch=async()=>{calls++;throw Error();};const req=request('POST',{});req.headers['x-csrf-token']='bad';const r=await call('submit',req);assert.equal(r.statusCode,403);assert.equal(calls,0);});
test('cross-origin mutation is refused even with matching token',async()=>{const req=request('POST',{});req.headers.origin='https://evil.invalid';assert.equal((await call('logout',req)).statusCode,403);});
test('researcher cannot approve a contribution',async()=>{withRole('researcher',()=>{throw Error('must not reach review');});const r=await call('review',request('POST',{id:itemId,version:1,status:'approved'}));assert.equal(r.statusCode,403);});
test('public output removes email, hidden name, and private path',async()=>{globalThis.fetch=async()=>response([{id:itemId,title:'Title',body:'Story',name:'Hidden',show_name:false,image_path:'private.webp'}]);const r=await call('exhibits',request());assert.equal(r.json.items[0].contributor,null);assert.equal(r.json.items[0].has_image,true);assert(!('name'in r.json.items[0]));assert(!('image_path'in r.json.items[0]));});
test('researcher queries omit contact fields and rejected entries; notes scoped to owner',async()=>{const seen=[];withRole('researcher',(u)=>{seen.push(u);if(u.pathname.endsWith('/hm_contributions'))return response([{id:itemId,title:'Title',status:'pending'}]);if(u.pathname.endsWith('/hm_notes'))return response([{contribution_id:itemId,note:'Mine'}]);throw Error(u.pathname);});const r=await call('entries',request());assert.equal(r.json.items[0].note,'Mine');const entries=seen.find(u=>u.pathname.endsWith('/hm_contributions'));assert.equal(entries.searchParams.get('status'),'in.(pending,approved)');assert(!entries.searchParams.get('select').includes('email'));assert.equal(seen.find(u=>u.pathname.endsWith('/hm_notes')).searchParams.get('user_id'),'eq.'+uid);});
test('private image cannot be fetched without a session',async()=>{globalThis.fetch=async url=>{assert(String(url).includes('/hm_contributions'));return response([{status:'pending',image_path:itemId+'.webp'}]);};const req=request('GET',undefined,'?id='+itemId);req.headers.cookie='';const r=await call('image',req);assert.equal(r.statusCode,404);});
test('review update detects stale version',async()=>{withRole('admin',(u,o)=>{assert.equal(o.method,'PATCH');assert.equal(u.searchParams.get('version'),'eq.1');return response([]);});const r=await call('review',request('POST',{id:itemId,version:1,status:'approved',review_note:''}));assert.equal(r.statusCode,409);});
test('valid submission inserts pending-by-default record without accepting client approval',async()=>{let record;globalThis.fetch=async(u,o)=>{if(String(u).includes('/rpc/hm_rate_limit'))return response(true);record=JSON.parse(o.body);return response(null,204);};const r=await call('submit',request('POST',{name:'اسم',email:'user@example.com',title:'حكاية',category:'story',body:'هذه حكاية طويلة كفاية لاختبار حفظ المشاركة.',consent:true,status:'approved',show_name:false}));assert.equal(r.statusCode,201);assert.match(r.json.reference,/^[A-F0-9]{16}$/);assert(!('status'in record));});
test('database rate limit stops submission',async()=>{globalThis.fetch=async()=>response(false);const r=await call('submit',request('POST',{}));assert.equal(r.statusCode,429);});
test('password sign-in yields opaque HttpOnly app cookie, not an Auth token',async()=>{let saved;globalThis.fetch=async(u,o)=>{const path=new URL(u).pathname;if(path.includes('/rpc/'))return response(true);if(path.endsWith('/token'))return response({user:{id:uid},access_token:'do-not-expose'});if(path.endsWith('/hm_profiles'))return response([{user_id:uid,name:'مدير',role:'admin'}]);if(path.endsWith('/hm_sessions')){if(o.method==='POST')saved=JSON.parse(o.body);return response(null,204);}throw Error(path);};const r=await call('login',request('POST',{email:'admin@example.com',password:'a long password'}));assert.equal(r.statusCode,200);assert.match(saved.token_hash,/^[a-f0-9]{64}$/);const c=r.headers['Set-Cookie'].find(x=>x.startsWith('hm_session='));assert(c.includes('HttpOnly'));assert(!String(r.data).includes('do-not-expose'));});
test('invalid image rejected; actual PNG decoded and converted to WebP',async()=>{await assert.rejects(()=>prepareImage(Buffer.from('not an image').toString('base64')),e=>e.status===422);const png=await sharp({create:{width:32,height:32,channels:3,background:'#cca255'}}).png().toBuffer();const result=await prepareImage(png.toString('base64'));assert.equal((await sharp(result).metadata()).format,'webp');});
