import {randomBytes,randomUUID,createHash,createHmac,timingSafeEqual} from 'node:crypto';
import sharp from 'sharp';
export const BUCKET='hail-memory-private';
export const MAX_IMAGE=2*1024*1024;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
export function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||!/^https:\/\/[a-z0-9.-]+(?::\d+)?\/?$/i.test(url))throw new HttpError(503,'الخدمة غير مهيأة. أضف متغيرات Supabase إلى إعدادات Vercel ثم أعد النشر.');return{url:url.replace(/\/$/,''),key};}
function cookies(req){const out={};for(const p of (req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim();}return out;}
function setCookie(req,res,name,value,age=28800){const old=res.getHeader('Set-Cookie')||[];const secure=process.env.VERCEL||req.socket?.encrypted;res.setHeader('Set-Cookie',[...(Array.isArray(old)?old:[old]),`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${age}${secure?'; Secure':''}`]);}
export function verifyCsrf(req){const c=cookies(req).hm_csrf,t=req.headers['x-csrf-token'];const origin=req.headers.origin;const secure=process.env.VERCEL||req.socket?.encrypted;const expected=`${secure?'https':'http'}://${req.headers.host}`;if(origin!==expected||typeof c!=='string'||typeof t!=='string'||!(/^[a-f0-9]{64}$/.test(c))||t.length!==64||!timingSafeEqual(Buffer.from(c),Buffer.from(t)))throw new HttpError(403,'طلب غير صالح أو جلسة منتهية. حدّث الصفحة وحاول مجددًا.');}
export function text(value,max,required=false){if(typeof value!=='string')throw new HttpError(422,'تحقق من الحقول المطلوبة.');const v=value.trim();if(v.length>max||(required&&!v))throw new HttpError(422,'تحقق من الحقول المطلوبة وأطوال النصوص.');return v;}
function id(value){if(typeof value!=='string'||!UUID.test(value))throw new HttpError(422,'معرّف غير صالح.');return value;}
function qs(object){return new URLSearchParams(Object.entries(object).filter(([,v])=>v!==undefined)).toString();}
async function upstream(path,{method='GET',body,headers={},binary=false,allowError=false}={}){const {url,key}=config();const h={apikey:key,...(key.startsWith('eyJ')?{Authorization:'Bearer '+key}:{}),...headers};let data=body;if(body!==undefined&&!Buffer.isBuffer(body)){h['Content-Type']='application/json';data=JSON.stringify(body);}let r;try{r=await fetch(url+path,{method,headers:h,body:data,signal:AbortSignal.timeout(15000)});}catch{throw new HttpError(503,'تعذّر الاتصال بخدمة البيانات. حاول مجددًا.');}if(!r.ok){if(allowError)return{failed:true,status:r.status};console.error('Supabase request failed',r.status,path.split('?')[0]);throw new HttpError(503,'تعذّر تنفيذ الطلب. تأكد من إعداد قاعدة البيانات والتخزين.');}if(binary)return Buffer.from(await r.arrayBuffer());if(r.status===204)return null;const raw=await r.text();return raw?JSON.parse(raw):null;}
function db(table,params,options={}){return upstream('/rest/v1/'+table+(params?'?'+qs(params):''),options);}
async function rate(req,scope,max,seconds){const{key}=config();const address=process.env.VERCEL?(req.headers['x-forwarded-for']||'').split(',')[0].trim():(req.socket?.remoteAddress||'local');const bucket=createHmac('sha256',key).update(scope+'|'+address).digest('hex');const allowed=await db('rpc/hm_rate_limit',null,{method:'POST',body:{p_key:bucket,p_limit:max,p_window:seconds}});if(allowed!==true)throw new HttpError(429,'محاولات كثيرة. حاول لاحقًا.');}
const digest=s=>createHash('sha256').update(s).digest('hex');
async function user(req,res,requiredRole){const token=cookies(req).hm_session;let result=null;if(token&&/^[a-f0-9]{64}$/.test(token)){const sessions=await db('hm_sessions',{token_hash:'eq.'+digest(token),select:'user_id,expires_at,last_seen',limit:1});const s=sessions?.[0];if(s&&Date.parse(s.expires_at)>Date.now()&&Date.now()-Date.parse(s.last_seen)<30*60*1000){const profiles=await db('hm_profiles',{user_id:'eq.'+s.user_id,active:'eq.true',select:'user_id,name,role',limit:1});if(profiles?.[0]){result=profiles[0];await db('hm_sessions',{token_hash:'eq.'+digest(token)},{method:'PATCH',body:{last_seen:new Date().toISOString()}});}}if(!result)setCookie(req,res,'hm_session','',0);}if(requiredRole&&!result)throw new HttpError(401,'سجّل الدخول للمتابعة.');if(requiredRole&&requiredRole!=='any'&&result.role!==requiredRole)throw new HttpError(403,'ليس لديك صلاحية لهذه العملية.');return result;}
async function bodyOf(req){if(req.body!==undefined){try{const data=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!data||Array.isArray(data)||typeof data!=='object')throw 0;if(Buffer.byteLength(JSON.stringify(data))>3*1024*1024)throw new HttpError(413,'حجم الطلب كبير. الحد الأقصى للصورة 2 ميجابايت.');return data;}catch(e){if(e instanceof HttpError)throw e;throw new HttpError(400,'صيغة الطلب غير صحيحة.');}}let raw='',bytes=0;for await(const b of req){bytes+=b.length;if(bytes>3*1024*1024)throw new HttpError(413,'حجم الطلب كبير.');raw+=b;}try{const data=JSON.parse(raw);if(!data||typeof data!=='object'||Array.isArray(data))throw 0;return data;}catch{throw new HttpError(400,'صيغة الطلب غير صحيحة.');}}
export async function prepareImage(base64){if(typeof base64!=='string'||!base64.length||base64.length>Math.ceil(MAX_IMAGE/3)*4||!/^[A-Za-z0-9+/]+={0,2}$/.test(base64))throw new HttpError(422,'صورة غير صالحة أو أكبر من 2 ميجابايت.');const data=Buffer.from(base64,'base64');if(data.length>MAX_IMAGE)throw new HttpError(422,'حجم الصورة أكبر من 2 ميجابايت.');try{const input=sharp(data,{limitInputPixels:16000000,animated:false});const meta=await input.metadata();if(!['jpeg','png','webp'].includes(meta.format)||(meta.pages||1)>1)throw 0;return await input.rotate().resize({width:1600,height:1600,fit:'inside',withoutEnlargement:true}).webp({quality:85}).toBuffer();}catch{throw new HttpError(422,'ارفع صورة JPG أو PNG أو WebP سليمة، لا تتجاوز 16 مليون بكسل.');}}
const pubFields='id,title,body,place,source,show_name,name,image_path,created_at';
async function run(action,req,res){const url=new URL(req.url,'http://local');const write=['login','logout','submit','review','note'].includes(action);if(req.method!==(write?'POST':'GET')){res.setHeader('Allow',write?'POST':'GET');throw new HttpError(405,'طريقة الطلب غير مسموحة.');}if(write){verifyCsrf(req);if(!String(req.headers['content-type']||'').startsWith('application/json'))throw new HttpError(415,'استخدم application/json.');}const body=write?await bodyOf(req):{};
 if(action==='session'){let token=cookies(req).hm_csrf;if(!token||!/^[a-f0-9]{64}$/.test(token)){token=randomBytes(32).toString('hex');setCookie(req,res,'hm_csrf',token);}return{csrf:token,user:await user(req,res),configured:!!(process.env.SUPABASE_URL&&(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY))};}
 if(action==='login'){await rate(req,'login',10,900);const email=text(body.email,190,true),password=body.password;if(typeof password!=='string'||password.length<1||password.length>1024)throw new HttpError(422,'أدخل كلمة المرور.');const auth=await upstream('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password},allowError:true});if(auth.failed||!auth.user?.id)throw new HttpError(401,'البريد أو كلمة المرور غير صحيحة، أو الحساب غير مؤكد.');const profile=(await db('hm_profiles',{user_id:'eq.'+auth.user.id,active:'eq.true',select:'user_id,name,role',limit:1}))?.[0];if(!profile)throw new HttpError(403,'هذا الحساب غير مخوّل لدخول الأرشيف.');const old=cookies(req).hm_session;if(old&&/^[a-f0-9]{64}$/.test(old))await db('hm_sessions',{token_hash:'eq.'+digest(old)},{method:'DELETE'});const token=randomBytes(32).toString('hex');await db('hm_sessions',null,{method:'POST',body:{token_hash:digest(token),user_id:profile.user_id,expires_at:new Date(Date.now()+8*3600000).toISOString()}});setCookie(req,res,'hm_session',token);setCookie(req,res,'hm_csrf',randomBytes(32).toString('hex'));return{user:profile};}
 if(action==='logout'){const token=cookies(req).hm_session;if(token&&/^[a-f0-9]{64}$/.test(token))await db('hm_sessions',{token_hash:'eq.'+digest(token)},{method:'DELETE'});setCookie(req,res,'hm_session','',0);setCookie(req,res,'hm_csrf','',0);return{ok:true};}
 if(action==='submit'){await rate(req,'submit',5,3600);const row={name:text(body.name,100,true),email:text(body.email,190,true),title:text(body.title,160,true),category:text(body.category,20,true),place:text(body.place??'',160),body:text(body.body,10000,true),source:text(body.source??'',400),show_name:body.show_name===true,consent_at:new Date().toISOString(),reference:randomBytes(8).toString('hex').toUpperCase()};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(row.email)||row.body.length<20||!['story','photo','object'].includes(row.category)||body.consent!==true)throw new HttpError(422,'تحقق من البريد والوصف والموافقة على المشاركة.');let path=null;if(body.image_base64){const image=await prepareImage(body.image_base64);path=randomUUID()+'.webp';await upstream('/storage/v1/object/'+BUCKET+'/'+path,{method:'POST',headers:{'Content-Type':'image/webp','x-upsert':'false'},body:image});row.image_path=path;}try{await db('hm_contributions',null,{method:'POST',body:row});}catch(e){if(path)try{await upstream('/storage/v1/object/'+BUCKET,{method:'DELETE',body:{prefixes:[path]}});}catch{console.error('Upload cleanup needed.');}throw e;}res.statusCode=201;return{reference:row.reference};}
 if(action==='exhibits'){const rows=await db('hm_contributions',{select:pubFields,status:'eq.approved',order:'created_at.desc',limit:60});return{items:rows.map(({name,show_name,image_path,...r})=>({...r,contributor:show_name?name:null,has_image:!!image_path}))};}
 if(action==='image'){const imageId=id(url.searchParams.get('id'));const row=(await db('hm_contributions',{id:'eq.'+imageId,select:'status,image_path',limit:1}))?.[0];if(!row?.image_path)throw new HttpError(404,'الصورة غير موجودة.');if(row.status!=='approved'){const u=await user(req,res);if(!u||(u.role==='researcher'&&row.status==='rejected'))throw new HttpError(404,'الصورة غير موجودة.');}if(!/^[0-9a-f-]+\.webp$/.test(row.image_path))throw new HttpError(404,'الصورة غير موجودة.');const image=await upstream('/storage/v1/object/authenticated/'+BUCKET+'/'+row.image_path,{binary:true});res.setHeader('Content-Type','image/webp');res.end(image);return null;}
 if(action==='entries'){const u=await user(req,res,'any');const page=Math.min(100000,Math.max(1,Number.parseInt(url.searchParams.get('page')||'1',10)||1));const q=(url.searchParams.get('q')||'').slice(0,120).replace(/[(),.*%_\\"\r\n]/g,' ').trim();const fields=u.role==='admin'?'*':'id,title,category,place,body,source,status,image_path,created_at';const params={select:fields,order:'created_at.desc',limit:21,offset:(page-1)*20};if(q)params.or=`(title.ilike.*${q}*,body.ilike.*${q}*,place.ilike.*${q}*)`;const status=url.searchParams.get('status');if(u.role==='researcher')params.status='in.(pending,approved)';else if(['pending','approved','rejected'].includes(status))params.status='eq.'+status;const category=url.searchParams.get('category');if(['story','photo','object'].includes(category))params.category='eq.'+category;let rows=await db('hm_contributions',params);const more=rows.length>20;rows=rows.slice(0,20);let notes=[];if(u.role==='researcher'&&rows.length)notes=await db('hm_notes',{select:'contribution_id,note',user_id:'eq.'+u.user_id,contribution_id:'in.('+rows.map(x=>x.id).join(',')+')'});return{items:rows.map(({image_path,...r})=>({...r,has_image:!!image_path,note:notes.find(n=>n.contribution_id===r.id)?.note||''})),more,page};}
 if(action==='review'){const u=await user(req,res,'admin');const itemId=id(body.id);if(!['pending','approved','rejected'].includes(body.status)||!Number.isSafeInteger(body.version)||body.version<1)throw new HttpError(422,'بيانات المراجعة غير صحيحة.');const rows=await db('hm_contributions',{id:'eq.'+itemId,version:'eq.'+body.version,select:'id,version'},{method:'PATCH',headers:{Prefer:'return=representation'},body:{status:body.status,review_note:text(body.review_note??'',3000),reviewed_by:u.user_id,reviewed_at:new Date().toISOString(),version:body.version+1}});if(!rows?.length)throw new HttpError(409,'تغيرت المشاركة. حدّث القائمة قبل المراجعة مجددًا.');return{ok:true};}
 if(action==='note'){const u=await user(req,res,'researcher'),itemId=id(body.id);const row=(await db('hm_contributions',{id:'eq.'+itemId,status:'in.(pending,approved)',select:'id',limit:1}))?.[0];if(!row)throw new HttpError(404,'المشاركة غير متاحة.');await db('hm_notes',{on_conflict:'contribution_id,user_id'},{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:{contribution_id:itemId,user_id:u.user_id,note:text(body.note??'',5000),updated_at:new Date().toISOString()}});return{ok:true};}
 throw new HttpError(404,'غير موجود.');
}
export function handler(action){return async(req,res)=>{res.setHeader('Cache-Control','private, no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Type','application/json; charset=utf-8');try{const data=await run(action,req,res);if(data!==null)res.end(JSON.stringify(data));}catch(error){if(!(error instanceof HttpError))console.error('Unhandled API error',error.name);res.statusCode=error.status||500;res.end(JSON.stringify({error:error instanceof HttpError?error.message:'تعذّر تنفيذ الطلب. حاول مجددًا.'}));}};}
